---
services:
  foods-api-base:
    image: foods-api-image
    build:
      context: .
    container_name: foods-api-base
    environment:
      - VIRTUAL_HOST=foods-api-app.docker
      - POSTGRES_HOST=foods-postgres
      - POSTGRES_DB=foods
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    volumes:
      - ${PWD}:/app
    command: ["echo", "I only exist to be extended so I'll just exit, thanks"]

  foods-api:
    extends: foods-api-base
    container_name: foods-api-app
    depends_on:
     - foods-postgres
    ports:
      - "5000:8000"
    command: ["uvicorn", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8000", "app:app"]

  foods-postgres:
    container_name: foods-postgres
    image: postgres:14.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      VIRTUAL_HOST: food-postgres.docker
      POSTGRES_DB: foods
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: '5432'
    ports:
      - "5790:5432"
