"""create table food

Revision ID: 135abb12ecec
Revises: 44c7a74892cd
Create Date: 2023-07-07 23:23:32.067925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '135abb12ecec'
down_revision = '36cdfcd15269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('size', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('category', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('contents', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('time_to_be_prepared', sa.Integer(), nullable=False),
                    sa.Column('calories', sa.Integer(), nullable=False),
                    sa.Column('food_number', sa.Integer(), sa.Identity(always=False, start=100, cycle=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id', name='food_pk'),
                    sa.UniqueConstraint('food_number', name='food_number_key')
                    )
    op.create_table('contents',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('food_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('calories', sa.Integer(), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='contents_food_food_id_fk'),
                    sa.PrimaryKeyConstraint('id', name='id_pk'),
                    sa.UniqueConstraint('name', name='name_key')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents')
    op.drop_table('food')
    # ### end Alembic commands ###
